spider:
  enable: false
#分页pageHelper
pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  page-size-zero: true
spring:
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  # 404会抛出错误设置,防止找不到路径http返回码还是200
  mvc:
    throw-exception-if-no-handler-found: true
  # 404会抛出错误设置,防止找不到路径http返回码还是200
  resources:
    add-mappings: false
